### ISSUE TITLE
Project Restructuring Checklist

### ISSUE THREAD

**Issue by akalicki** [alexandramedway/odds#54]
TODO to get functions into a working state:
 - [ ] #50: Buy ingredients for quesadillas
 - [x] #51: Initial working SAST with scoping
 - [x] #55: SAST type inference and semantic checking
 - [x] #66: SAST recursive function calls
 - [x] #52: Initial working PAST
 - [x] #53: Code generation from PAST (should be an easy refactor of `generator.ml` and `printer.ml`)

Once we finish each of the above, we will create a pull request to merge it into `master-refactor`. When all tests pass, we will merge the refactored code into the `master` branch.

@lillyfwang @alexandramedway @dannyech
